language: python

sudo: required
python:
  - "3.7"
  - "3.6"
addons:
  chrome: stable

before_script: ci/setup.sh

install: pip install -r requirements.txt
script:
  - export PATH=`pwd`:$PATH
  - py.test -v